name: Build Docker image

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/docker.yml"
      - "docker/stable-diffusion-serving.Dockerfile"

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  IMAGE_NAME: ghcr.io/gabriel-milan/stable-diffusion

jobs:
  build-container:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish Prefect Agent image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA -f docker/stable-diffusion-serving.Dockerfile .
          docker build -t $IMAGE_NAME:latest -f docker/stable-diffusion-serving.Dockerfile .
          echo $GH_PAT | docker login ghcr.io -u gabriel-milan --password-stdin
          docker push $IMAGE_NAME:$GITHUB_SHA
          docker push $IMAGE_NAME:latest
